### ISSUE TITLE
Cannot complete 'npm install' on Android 8.1.0

### ISSUE THREAD

**Issue by Tikotik** [Deezloader/DeezLoader#7]
termux Log:
`0 info it worked if it ends with ok
1 verbose cli [ '/data/data/com.termux/files/usr/bin/node',
1 verbose cli   '/data/data/com.termux/files/usr/bin/npm',
1 verbose cli   'install' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose npm-session 68948f25a445035d
5 verbose stack TypeError: Cannot read property 'length' of undefined
5 verbose stack     at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js:5:61)
5 verbose stack     at Module._compile (module.js:652:30)
5 verbose stack     at Object.Module._extensions..js (module.js:663:10)
5 verbose stack     at Module.load (module.js:565:32)
5 verbose stack     at tryModuleLoad (module.js:505:12)
5 verbose stack     at Function.Module._load (module.js:497:3)
5 verbose stack     at Module.require (module.js:596:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/index.js:3:14)
5 verbose stack     at Module._compile (module.js:652:30)
5 verbose stack     at Object.Module._extensions..js (module.js:663:10)
5 verbose stack     at Module.load (module.js:565:32)
5 verbose stack     at tryModuleLoad (module.js:505:12)
5 verbose stack     at Function.Module._load (module.js:497:3)
5 verbose stack     at Module.require (module.js:596:17)
5 verbose stack     at require (internal/module.js:11:18)
6 verbose cwd /data/data/com.termux/files/home/DeezLoader/app/DeezLoader/app
7 verbose Linux 3.18.116-UniverseV1
8 verbose argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "install"
9 verbose node v8.11.4
10 verbose npm  v5.6.0
11 error Cannot read property 'length' of undefined
12 verbose exit [ 1, true ]
`

**Comment by pateldhruv1993** [comment]
Same problem here. Undefined lenght
